---
kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:12.16.0-alpine
    commands:
      - yarn install

  - name: test
    image: node:12.16.0-alpine
    commands:
      - yarn test
      - apk add --no-cache git
      - yarn codecov
    environment:
      CODECOV_TOKEN:
        from_secret: codecov-token

---
kind: signature
hmac: 78898ea4f590e870aee53498621a2f9aaad234fad00f2c5956413a0863921850
