kind: pipeline
name: default

steps:
  - name: install
    image: node:10.15.3-alpine
    commands:
      - yarn install

  - name: test
    image: node:10.15.3-alpine
    commands:
      - yarn test
      - apk add --no-cache git
      - yarn codecov
    environment:
      CODECOV_TOKEN:
        from_secret: codecov-token
